### ISSUE TITLE
Apply a preset to a model based on a substring of the filename or filepath (e.g. for Lightning models, etc.)

### ISSUE THREAD

**Issue by brendanhoar** [mcmonkeyprojects/SwarmUI#351] opened 2024-10-24 16:17 UTC
### Feature Idea

Request:

An option to apply a preset if the filename of the model matched a particular substring.

Implemented via a new tab with a list of mappings from substring to presets that the user created:

```
Substring     Preset Name
4step         Auto/4step-Lightning-4s-cfg1-...
8step         Auto/8step-Lightning-8s-cfg1-....
lightning     Auto/4step-Lightning-4s-cfg1-...
```

I could see utility for allowing multiple matches with a merge of parameters, with a rule on first or last parameter taking priority. First match only would be fine of course.

Setting a preset manually (via tab or inline) would override the parameters of this (or merge with priority?) if they were set.

Perhaps a third column to toggle if the match should be against the filename proper or include the subpath as well.

This might also be a candidate to be done as an extension.

B

**Comment by mcmonkey4eva** [comment] 2024-10-25 11:02
Duplicate of https://github.com/mcmonkeyprojects/SwarmUI/issues/274

**Closed by mcmonkey4eva** 2024-10-25 11:02 UTC
Labels: Feature
