### ISSUE TITLE
[Feature Request] Support for GGUF format in swarmUI

### ISSUE THREAD

**Issue by bearbro95** [mcmonkeyprojects/SwarmUI#180] opened 2024-08-17 23:55 UTC
### Feature Idea

I would love to see GGUF support in swarmUI.

**Comment by mcmonkey4eva** [comment] 2024-08-18 09:48
duplicate of https://github.com/mcmonkeyprojects/SwarmUI/issues/165

**Closed by mcmonkey4eva** 2024-08-18 09:48 UTC
Labels: Feature
