### ISSUE TITLE
Aspect Ration Swapper Button

### ISSUE THREAD

**Issue by SouthbayJay** [mcmonkeyprojects/SwarmUI#256] opened 2024-09-12 03:56 UTC
### Feature Idea

Request for an aspect ration swap button as discussed on discord here.... 

[https://discord.com/channels/1243166023859961988/1243185862234210389/1283634215753093186](url)

**Comment by mcmonkey4eva** [comment] 2024-09-12 04:35
duplicate of https://github.com/mcmonkeyprojects/SwarmUI/issues/210

**Closed by mcmonkey4eva** 2024-09-12 04:35 UTC
Labels: Feature, Frontend
