### ISSUE TITLE
Improved upscale after generation

### ISSUE THREAD

**Issue by TheNarcDad97** [mcmonkeyprojects/SwarmUI#253] opened 2024-09-09 14:38 UTC
### Feature Idea

Replace the “2x upscale” option after image generation with an option to upscale using the current upscale settings. At the moment it’s not a smooth experience to quickly upscale the best generated images with your preferred settings, so allowing us to quickly upscale the image would be a very welcome feature.

**Comment by mcmonkey4eva** [comment] 2024-09-10 08:09
duplicate of https://github.com/mcmonkeyprojects/SwarmUI/issues/122

**Closed by mcmonkey4eva** 2024-09-10 08:09 UTC
Labels: Feature
